export const icons = {
	bell: "icons/bell.svg#bell",
	bellSlash: "icons/bell-slash.svg#bell-slash",
	bookmark: "icons/bookmark.svg#bookmark",
	bookmarkSlash: "icons/bookmark-slash.svg#bookmark-slash",
	checkCircleFill: "icons/check-circle-fill.svg#check-circle-fill",
	checkCircle: "icons/check-circle.svg#check-circle",
	check: "icons/check.svg#check",
	commentDiscussion: "icons/comment-discussion.svg#comment-discussion",
	inbox: "icons/inbox.svg#inbox",
	moon: "icons/moon.svg#moon",
	mortarBoard: "icons/mortar-board.svg#mortar-board",
	notification: "icons/notification.svg#notification",
	plus: "icons/plus.svg#plus",
	question: "icons/question.svg#question",
}
